### ISSUE TITLE
Similarities to Nim?

### ISSUE THREAD

**Issue by 0atman** [eerimoq/mys#1]
This is a great project, with a similar feel to Nim - do steal as much from Nim as you can!
How does the "rust-like" packaging compare to Nimble?

**Comment by eerimoq** [comment]
Anything in particular you want me to "steal" from Nim?

I don't know how nimble works in detail, but it's probably similar to the planned packaging in Mys. The main goal is to make it easy to share your code with other projects.

**Comment by eerimoq** [comment]
Closing as there is no response.

**Comment by 0atman** [comment]
cool, thanks for the packaging info!
