### ISSUE TITLE
Pattern Matching invalid syntax

### ISSUE THREAD

**Issue by phillvancejr** [eerimoq/mys#10]
Does pattern matching work currently? I'm copying the pattern matching example but getting an invalid syntax error.

**Comment by eerimoq** [comment]
No it does not. Not much work at the moment to be honest, just as the important message in the readme says. Pattern matching will is implemented on branch in the CPython project. It will be part of Python 3.10 as I understand it, which is released late next year. Mys could of course use the parser implementation from the branch, but right now it's not prioritized.

You can have a look [here](https://www.python.org/dev/peps/pep-0634/) if you want to know more about pattern matching in Python.

**Comment by phillvancejr** [comment]
Thanks! Also I was able to compile the transpiled Mys code to Webassembly as an interesting aside :D
