### ISSUE TITLE
general question about mys

### ISSUE THREAD

**Issue by mpage38** [eerimoq/mys#4]
Just by curiosity: why didn't you choose to transpile PEP 484 'typed' python to __Cython__ ? My point is: python is not just python in the sense that there are many python, cython, C, C++  libraries in the python ecosystem. It will be difficult to deal with this, using your C++ transpilation approach, I think

**Comment by eerimoq** [comment]
Yeah, I know. Not being compatible with CPython makes most, if not all, third party packages unusable. Python's standard library has to be re-implemented as well. So far my approach is to create a lean and reasonably efficient (in terms of RAM and CPU) language, and at the same time keep it as easy to read and write as Python. Mys is mainly targets embedded systems. It's not always possible to run the CPython interpreter on those systems. Also, the plan is to allow executing threads in parallel. That is, no GIL. I'm of course not sure that the transpiled code will perform better than CPython, but that's the goal.

Btw, [mypyc](https://github.com/python/mypy/tree/master/mypyc) look promising to make Python modules faster. I think that is a good match for appliactions that uses the CPython interpreter and need better performance. PyPy is of course also an option.

**Comment by mpage38** [comment]
I see. It might be a good idea to add a "Rationale" section in the readme of your project containing the last part of your first paragraph above.

**Comment by eerimoq** [comment]
I added a very short rationale in the readme. Thanks =)
