### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by RealAAbraham** [eerimoq/mys#5]
Currently building my own language in Python [here](https://hexlang.com). How did you implement functions and flow-control. I am awed at what you have achieved with MYS.

**Comment by eerimoq** [comment]
Hi!

Nice job with HEX LANG =)

Mys is currently using Python's ast-module to transform the source code to an abstract syntax tree (AST). The AST is then converted into C++ source code, which is then compiled. This is fairly easy to do as Python and C++ are similar (classes, functions, exceptions, etc. exist in both languages).

Later on I might generate C source code for potentially smaller binaries, or even implement support for Mys in LLVM, but that's a lot of work and is currently out of scope.

**Comment by RealAAbraham** [comment]
Hello to you. :) Thank you very much! :) Hmm, I'll have a look at those parts of your code, but good to know that I can use the AST module. Thought it only built trees of Python code. 🤔 Haha yes, same here though. Yup, totally understand, Hex is also still in it's infancy. And yes! You bet I will!!! Same goes for you. 😉

**Comment by RealAAbraham** [comment]
Hi Eriq, I am currently extremely busy with other things in my life, I wilk continue my work on Hex and help out with Mys once things become more relaxed. Hope you understand. :) Got a lot going on at the moment.🤪

**Comment by eerimoq** [comment]
No problem, I understand =)
