### ISSUE TITLE
Collaboration / Tantilla 

### ISSUE THREAD

**Issue by stefanhaustein** [eerimoq/mys#6]
Hi, thanks for the invitation :)

I'd like to keep my focus on the mobile IDE part, but perhaps there are some areas where we can collaborate, e.g. typed examples and test cases, language subset overlap etc.? Did not make the list promised on hacker news yet O:)

**Comment by eerimoq** [comment]
Ok =)

Let's see what happens. I have absolutely no expectations, it would be fun to collaborate though =)

**Comment by stefanhaustein** [comment]
I have tried to start a doc but then realized I just know too little about Mys to make it meaningful... Can you be more explicit about your plans for compatibility to pyhton vs. "cleanness"? 

What are you adding to regular "typed python", what are you taking away? (I guess this would be best answered on your main project page or a dedicated "coming from python page" -- opposed to here)

Do you think it would be possible to create reasonable test cases / examples that are 

- valid typed python and
- run in mys at the same time?
