### ISSUE TITLE
linker error on MacOS

### ISSUE THREAD

**Issue by phillvancejr** [eerimoq/mys#9]
Hi just trying out mys, when I try to  run the foo example on MacOS High Sierra I get a linker error
```
ld: library not found for -lcrt0.o
```

**Comment by eerimoq** [comment]
The problem is probably the static linking. I can make it dynamic if you want to give it a try. Did you install using pip, or did you clone this repository?

**Comment by phillvancejr** [comment]
I used pip. And yes you're right, I went into the makefile and removed both --gc-sections and -static and it builds now. It looks like these options are not supported on MacOS

**Comment by eerimoq** [comment]
Ok, I'll remove these and create a new release.

**Comment by eerimoq** [comment]
Done. Run `pip3 install -U mys`, or similar. `-U` means upgrade.

**Comment by phillvancejr** [comment]
Awesome, it works!
